name: preab_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pocketbase: ^0.2.0
  future_manager: ^1.0.0
  sura_flutter: ^1.4.2
  preab:
    path: ../
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
